FROM node:18

RUN mkdir -p /home/app/front

RUN chown -R node:node /home/app/front

WORKDIR /home/app/front

COPY --chown=node:node icarus-web/ ./

USER node

RUN npm install

EXPOSE 3000

# CMD ["node", "src/index.js"]
CMD ["npm", "start"]
